name: PHP Linting
on: pull_request
jobs:
    phplint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "laravel-pint"
              uses: aglipanci/laravel-pint-action@2.0.0
              with:
                  preset: laravel
                  verboseMode: true
            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v5
                with:
                    commit_message: PHP Linting (Pint)
                    skip_fetch: true
